### ISSUE TITLE
-07 Changes Checklist

### ISSUE THREAD

**Issue by anewton1998** [arineng/jcr#22]
- [ ] Rework examples to have new `$` and `=` and repetition syntax
- [ ] Remove Appendix C Combining Multiple Rulesets (Experimental)
- [ ] Update RFC 4627 example to RFC 7159 #15
- [ ] Update with final ABNF from jcrvalidator

**Comment by anewton1998** [comment]
@codalogic can you see if you have perms to update the checklist?
